# Generated by Django 4.2.4 on 2024-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='./media/defualt.jpg', upload_to='User Profile'),
        ),
    ]
