# Generated by Django 4.2.4 on 2024-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profile_img_expence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence',
            name='user',
        ),
        migrations.AddField(
            model_name='expence',
            name='last_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expence',
            name='remaing_students_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expence',
            name='started_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
