# Generated by Django 4.2.4 on 2024-10-14 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_expence_user_givenexpence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givenexpence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
