# Generated by Django 4.2.4 on 2024-10-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_givenexpence_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givenexpence',
            name='discription',
        ),
        migrations.AddField(
            model_name='givenexpence',
            name='status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
